### ISSUE TITLE
Drop sdl runtime dep

### ISSUE THREAD

**Issue by shevernitskiy** [littledivy/wgui#13]
As I understand, sdl is needed to obtain generate textures from ttf glyph info? Could it be somehow moved to "compile time" to drop runtime dependency on sdl?
Like, we should check what glyphs we need, then generate textures, store it as uint8 bytes and bake it into binary. Or something like it, i'm not an expert:)

**Comment by littledivy** [comment]
SDL is needed for window creation and events. It cannot be dropped.

There is tracking issue for supporting other windowing systems other than SDL. https://github.com/littledivy/wgui/issues/5

**Comment by shevernitskiy** [comment]
Oh, ok. Will track it:)
